# Generated by Django 3.1.8 on 2021-04-24 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='番地/部屋番号')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('state', models.CharField(max_length=100, verbose_name='都道府県')),
                ('zip', models.CharField(max_length=100, verbose_name='郵便番号')),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '配送先住所',
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='番地/部屋番号')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('state', models.CharField(max_length=100, verbose_name='都道府県')),
                ('zip', models.CharField(max_length=100, verbose_name='郵便番号')),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '請求先住所',
            },
        ),
    ]
