# Generated by Django 3.1.8 on 2021-04-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='セール価格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('pickup', models.BooleanField(default=False, verbose_name='トップページ厳選')),
                ('featured', models.BooleanField(default=False, verbose_name='トップページおすすめ')),
                ('draft', models.BooleanField(default=False, verbose_name='非公開にする')),
                ('fav_users', models.ManyToManyField(blank=True, related_name='fav_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '商品',
            },
            bases=('wagtailcore.page',),
        ),
    ]
