# Generated by Django 3.1.8 on 2021-04-22 14:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ItemParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URLの一部として表示されるものです。後で変更すると問題が生じる可能性があります。また、他の商品と重複するものは使わないで下さい。', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': '親カテゴリー',
                'verbose_name_plural': '親カテゴリー',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='itemdetailpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='商品説明'),
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='store.itemdetailpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_taggeditem_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URLの一部として表示されるものです。後で変更すると問題が生じる可能性があります。また、他の商品と重複するものは使わないで下さい。', max_length=255, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, help_text='親カテゴリーを先に登録して下さい。親カテゴリーが必要ないカテゴリーは、このフィールドは空のまま登録して下さい。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.itemparentcategory', verbose_name='親カテゴリー(オプション)')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='itemdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='items', to='store.ItemCategory', verbose_name='カテゴリー(option)'),
        ),
        migrations.AddField(
            model_name='itemdetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='store.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
