# Generated by Django 3.1.8 on 2021-04-23 06:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('store', '0002_auto_20210422_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URLの一部として表示されるものです。後で変更すると問題が生じる可能性があります。また、他の商品と重複するものは使えません。', max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='itemdetailpage',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='下書き'),
        ),
        migrations.AlterField(
            model_name='itemdetailpage',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='おすすめ'),
        ),
        migrations.AlterField(
            model_name='itemdetailpage',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='厳選'),
        ),
        migrations.AlterField(
            model_name='itemparentcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URLの一部として表示されるものです。後で変更すると問題が生じる可能性があります。また、他の商品と重複するものは使えません。', max_length=255, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='ItemSlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('slide_img_alt', models.CharField(blank=True, help_text='画像が表示されない時に挿入されるテキストです。', max_length=100, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_images', to='store.itemdetailpage')),
                ('slide_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
