# Generated by Django 3.1.8 on 2021-04-23 07:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210423_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_option', to='store.itemdetailpage')),
            ],
            options={
                'verbose_name_plural': '商品サイズ',
                'unique_together': {('item', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_option', to='store.itemdetailpage')),
            ],
            options={
                'verbose_name_plural': '商品カラー',
                'unique_together': {('item', 'value')},
            },
        ),
    ]
