# Generated by Django 3.1.8 on 2021-04-24 05:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('store', '0004_coloroption_sizeoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetailpage',
            name='draft',
        ),
        migrations.AddField(
            model_name='itemdetailpage',
            name='list_image',
            field=models.ForeignKey(blank=True, help_text='商品リストにサムネイルとして表示される画像です。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='リスト画像'),
        ),
        migrations.AddField(
            model_name='itemdetailpage',
            name='list_img_alt',
            field=models.CharField(blank=True, help_text='画像が表示されない時に挿入されるテキストです。', max_length=100, null=True, verbose_name='代替テキスト'),
        ),
        migrations.AlterField(
            model_name='itemdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='items', to='store.ItemCategory', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='itemslideimages',
            name='slide_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='itemslideimages',
            name='slide_img_alt',
            field=models.CharField(blank=True, help_text='画像が表示されない時に挿入されるテキストです。', max_length=100, null=True, verbose_name='代替テキスト'),
        ),
    ]
