# Generated by Django 3.1.8 on 2021-04-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210424_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdetailpage',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
