# Generated by Django 3.1.8 on 2021-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210427_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shippment_line', models.IntegerField(blank=True, null=True, verbose_name='送料無料最低価格')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='送料')),
                ('order_history_paginate_by', models.IntegerField(default=5, verbose_name='購入履歴1ページ表示数')),
                ('order_list_paginate_by', models.IntegerField(default=5, verbose_name='注文管理1ページ表示数')),
            ],
            options={
                'verbose_name': '注文関連設定',
                'verbose_name_plural': '注文関連設定',
            },
        ),
    ]
