# Generated by Django 3.1.8 on 2021-05-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='発送済み'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name='注文確定日'),
        ),
    ]
