# Generated by Django 3.1.14 on 2022-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_itemlistingpagination'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlistingpagination',
            name='tag_page',
            field=models.IntegerField(default=4, verbose_name='タグページ'),
        ),
        migrations.AlterField(
            model_name='itemlistingpagination',
            name='category_page',
            field=models.IntegerField(default=4, verbose_name='カテゴリーページ'),
        ),
        migrations.AlterField(
            model_name='itemlistingpagination',
            name='listing_page',
            field=models.IntegerField(default=4, verbose_name='商品一覧'),
        ),
    ]
