# Generated by Django 3.1.8 on 2021-04-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='custom_title',
        ),
    ]
