# Generated by Django 3.1.8 on 2021-05-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='content',
            new_name='other_contents',
        ),
    ]
