# Generated by Django 3.1.8 on 2021-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210507_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='下書きにする'),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='whatsnew',
            field=models.BooleanField(default=False, verbose_name="What's New"),
        ),
    ]
