# Generated by Django 3.1.8 on 2021-05-21 12:07

from django.db import migrations, models
import modelcluster.fields
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210514_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'その他執筆者', 'verbose_name_plural': 'その他執筆者'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'ブログカテゴリー', 'verbose_name_plural': 'ブログカテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='blogdetailpage',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AlterModelOptions(
            name='blogparentcategory',
            options={'ordering': ['name'], 'verbose_name': 'ブログ親カテゴリー', 'verbose_name_plural': 'ブログ親カテゴリー'},
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='posts', to='blog.BlogCategory', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='other_contents',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.core.blocks.CharBlock(heading='Image Alt (Option)', help_text='Add some alt text', max_length=100, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))], blank=True, null=True, verbose_name='追加コンテンツ'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='whatsnew',
            field=models.BooleanField(default=False, verbose_name="What's Newに表示"),
        ),
    ]
