# Generated by Django 3.1.8 on 2021-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210525_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagination',
            name='featured',
        ),
        migrations.AddField(
            model_name='blogpagination',
            name='whatsnew_home',
            field=models.IntegerField(default=3, verbose_name='トップページおすすめ'),
        ),
    ]
