# Generated by Django 4.1.9 on 2025-01-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_taggedpost_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='draft',
        ),
    ]
