# Generated by Django 3.1.8 on 2021-05-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_subscriptionform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'サイト設定', 'verbose_name_plural': 'サイト設定'},
        ),
    ]
