# Generated by Django 3.1.14 on 2022-11-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_settings', '0004_auto_20210521_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo_image',
            field=models.ForeignKey(blank=True, help_text='幅200px以上のものを使用して下さい', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name=''),
        ),
    ]
