# Generated by Django 3.1.8 on 2021-05-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'ニュースレター購読者', 'verbose_name_plural': 'ニュースレター購読者'},
        ),
    ]
